title: Brendan Kariithi
description: EE-SWE Portfolio
theme: just-the-docs

url: https.//https://bkariithi.github.io/Brendan-Website

Template Repository: https://github.com/bkariithi/Brendan-Website
